# -*- coding: utf-8 -*-
"""class103.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P95wTXo1u0e-UjFCqyn96Ilwvj_PN-1s
"""

import pandas as pd
df=pd.DataFrame()
print(df)

import pandas as pd
data=[[1,12,15],[2,34,56]]
df=pd.DataFrame(data)
print(df)

import pandas as pd
import plotly.express as px
df=pd.read_csv("line_chart.csv")
fig=px.line(df,x='Per capita income',y="Year",color="Country",title="Per capita income of countries")
fig.show()

import pandas as pd
import plotly.express as px
df=pd.read_csv("data.csv")
fig=px.bar(df,x='Country',y='Population',color='Country')
fig.show()

import pandas as pd
import plotly.express as px
df=pd.read_csv("data.csv")
fig=px.scatter(df,x='Population',y='Percentage',color='Country',title='Year and percentage',size='Percentage',size_max=50)
fig.show()